export default [
  {
    endStationCode: "AOH",
    remainTicketCount: 0,
    dTimeStr: "202002101736",
    sort: 4,
    time: "4时29分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京南",
    date: "2020-11-15",
    remainTicket: "0张",
    priceMsg: "¥443.5",
    dptStationCode: "VNP",
    trainType: "高速动车",
    timeInMinute: 269,
    dStationInfo: true,
    trainStatus: 4,
    dTime: "17:36",
    startStationCode: "VNP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: false,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "1345",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC%E5%8D%97&endStation=%E5%8D%97%E4%BA%AC%E5%8D%97&trainNum=G157&date=2020-11-13&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E4%BA%8C%E7%AD%89%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "二等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "4",
        price: "443.5",
        countColor: -1,
        studentPrice: "333",
        tagColor: -1,
        count: 0,
      },
      {
        type: "一等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "3",
        price: "748.5",
        countColor: -1,
        studentPrice: "748.5",
        tagColor: -1,
        count: 0,
      },
      {
        type: "商务座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "13",
        price: "1403.5",
        countColor: -1,
        studentPrice: "1403.5",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: true,
    remainTicketColor: -39424,
    aStation: "南京南",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002102205",
    remainTicketType: 0,
    aTime: "22:05",
    dayAfter: "",
    tagColor: -1,
    trainNumber: "G157",
    arrStationCode: "NKH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "AOH",
    remainTicketCount: 0,
    dTimeStr: "202002101746",
    sort: 6,
    time: "4时52分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京南",
    date: "2020-11-16",
    remainTicket: "0张",
    priceMsg: "¥443.5",
    dptStationCode: "VNP",
    trainType: "高速动车",
    timeInMinute: 292,
    dStationInfo: true,
    trainStatus: 4,
    dTime: "17:46",
    startStationCode: "VNP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: false,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "1460",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC%E5%8D%97&endStation=%E5%8D%97%E4%BA%AC%E5%8D%97&trainNum=G159&date=2020-11-13&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E4%BA%8C%E7%AD%89%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "二等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "4",
        price: "443.5",
        countColor: -1,
        studentPrice: "333",
        tagColor: -1,
        count: 0,
      },
      {
        type: "一等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "3",
        price: "748.5",
        countColor: -1,
        studentPrice: "748.5",
        tagColor: -1,
        count: 0,
      },
      {
        type: "商务座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "13",
        price: "1403.5",
        countColor: -1,
        studentPrice: "1403.5",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: true,
    remainTicketColor: -39424,
    aStation: "南京南",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002102238",
    remainTicketType: 0,
    aTime: "22:38",
    dayAfter: "",
    tagColor: -1,
    trainNumber: "G159",
    arrStationCode: "NKH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "NKH",
    remainTicketCount: 0,
    dTimeStr: "202002101835",
    sort: 5,
    time: "4时35分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京南",
    date: "2020-11-17",
    remainTicket: "0张",
    priceMsg: "¥443.5",
    dptStationCode: "VNP",
    trainType: "高速动车",
    timeInMinute: 275,
    dStationInfo: true,
    trainStatus: 4,
    dTime: "18:35",
    startStationCode: "VNP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: true,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "1375",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC%E5%8D%97&endStation=%E5%8D%97%E4%BA%AC%E5%8D%97&trainNum=G203&date=2020-11-13&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E4%BA%8C%E7%AD%89%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "二等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "4",
        price: "443.5",
        countColor: -1,
        studentPrice: "333",
        tagColor: -1,
        count: 0,
      },
      {
        type: "一等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "3",
        price: "748.5",
        countColor: -1,
        studentPrice: "748.5",
        tagColor: -1,
        count: 0,
      },
      {
        type: "商务座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "13",
        price: "1403.5",
        countColor: -1,
        studentPrice: "1403.5",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: true,
    remainTicketColor: -39424,
    aStation: "南京南",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002102310",
    remainTicketType: 0,
    aTime: "23:10",
    dayAfter: "",
    tagColor: -1,
    trainNumber: "G203",
    arrStationCode: "NKH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "HZH",
    remainTicketCount: 0,
    dTimeStr: "202002101858",
    sort: 11,
    time: "10时26分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京",
    date: "2020-11-12",
    remainTicket: "0张",
    priceMsg: "¥148.5",
    dptStationCode: "BJP",
    trainType: "直达特快",
    timeInMinute: 626,
    dStationInfo: false,
    trainStatus: 4,
    dTime: "18:58",
    startStationCode: "BTC",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: false,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "1669",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC&endStation=%E5%8D%97%E4%BA%AC&trainNum=Z281&date=2020-11-12&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E7%A1%AC%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "硬座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "1",
        price: "148.5",
        countColor: -1,
        studentPrice: "75",
        tagColor: -1,
        count: 0,
      },
      {
        type: "硬卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "5",
        price: "272.5",
        countColor: -1,
        studentPrice: "199",
        tagColor: -1,
        count: 0,
      },
      {
        type: "软卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "8",
        price: "415.5",
        countColor: -1,
        studentPrice: "415.5",
        tagColor: -1,
        count: 0,
      },
      {
        type: "无座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "0",
        price: "148.5",
        countColor: -1,
        studentPrice: "75",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: false,
    remainTicketColor: -39424,
    aStation: "南京",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002110524",
    remainTicketType: 0,
    aTime: "05:24",
    dayAfter: "+1",
    tagColor: -1,
    trainNumber: "Z281",
    arrStationCode: "NJH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "AOH",
    remainTicketCount: 0,
    dTimeStr: "202002101900",
    sort: 0,
    time: "3时13分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京南",
    date: "2020-11-13",
    remainTicket: "0张",
    priceMsg: "¥443.5",
    dptStationCode: "VNP",
    trainType: "高速动车",
    timeInMinute: 193,
    dStationInfo: true,
    trainStatus: 4,
    dTime: "19:00",
    startStationCode: "VNP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: false,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "965",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC%E5%8D%97&endStation=%E5%8D%97%E4%BA%AC%E5%8D%97&trainNum=G17&date=2020-11-13&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E4%BA%8C%E7%AD%89%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "二等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "4",
        price: "443.5",
        countColor: -1,
        studentPrice: "333",
        tagColor: -1,
        count: 0,
      },
      {
        type: "一等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "3",
        price: "748.5",
        countColor: -1,
        studentPrice: "748.5",
        tagColor: -1,
        count: 0,
      },
      {
        type: "商务座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "13",
        price: "1403.5",
        countColor: -1,
        studentPrice: "1403.5",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: true,
    remainTicketColor: -39424,
    aStation: "南京南",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002102213",
    remainTicketType: 0,
    aTime: "22:13",
    dayAfter: "",
    tagColor: -1,
    trainNumber: "G17",
    arrStationCode: "NKH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "HGH",
    remainTicketCount: 0,
    dTimeStr: "202002101904",
    sort: 1,
    time: "3时13分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京南",
    date: "2020-11-14",
    remainTicket: "0张",
    priceMsg: "¥443.5",
    dptStationCode: "VNP",
    trainType: "高速动车",
    timeInMinute: 193,
    dStationInfo: true,
    trainStatus: 4,
    dTime: "19:04",
    startStationCode: "VNP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: false,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "965",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC%E5%8D%97&endStation=%E5%8D%97%E4%BA%AC%E5%8D%97&trainNum=G39&date=2020-11-14&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E4%BA%8C%E7%AD%89%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "二等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "4",
        price: "443.5",
        countColor: -1,
        studentPrice: "333",
        tagColor: -1,
        count: 0,
      },
      {
        type: "一等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "3",
        price: "748.5",
        countColor: -1,
        studentPrice: "748.5",
        tagColor: -1,
        count: 0,
      },
      {
        type: "商务座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "13",
        price: "1403.5",
        countColor: -1,
        studentPrice: "1403.5",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: true,
    remainTicketColor: -39424,
    aStation: "南京南",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002102217",
    remainTicketType: 0,
    aTime: "22:17",
    dayAfter: "",
    tagColor: -1,
    trainNumber: "G39",
    arrStationCode: "NKH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "SHH",
    remainTicketCount: 0,
    dTimeStr: "202002101908",
    sort: 2,
    time: "3时23分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京南",
    date: "2020-11-15",
    remainTicket: "0张",
    priceMsg: "¥443.5",
    dptStationCode: "VNP",
    trainType: "高速动车",
    timeInMinute: 203,
    dStationInfo: true,
    trainStatus: 4,
    dTime: "19:08",
    startStationCode: "VNP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: false,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "1015",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC%E5%8D%97&endStation=%E5%8D%97%E4%BA%AC%E5%8D%97&trainNum=G21&date=2020-11-15&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E4%BA%8C%E7%AD%89%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "二等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "4",
        price: "443.5",
        countColor: -1,
        studentPrice: "333",
        tagColor: -1,
        count: 0,
      },
      {
        type: "一等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "3",
        price: "748.5",
        countColor: -1,
        studentPrice: "748.5",
        tagColor: -1,
        count: 0,
      },
      {
        type: "商务座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "13",
        price: "1403.5",
        countColor: -1,
        studentPrice: "1403.5",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: true,
    remainTicketColor: -39424,
    aStation: "南京南",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002102231",
    remainTicketType: 0,
    aTime: "22:31",
    dayAfter: "",
    tagColor: -1,
    trainNumber: "G21",
    arrStationCode: "NKH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "HZH",
    remainTicketCount: 0,
    dTimeStr: "202002101916",
    sort: 9,
    time: "9时29分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京",
    date: "2020-11-15",
    remainTicket: "0张",
    priceMsg: "¥233",
    dptStationCode: "BJP",
    trainType: "动车组",
    timeInMinute: 569,
    dStationInfo: true,
    trainStatus: 4,
    dTime: "19:16",
    startStationCode: "BJP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: false,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "2086",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC&endStation=%E5%8D%97%E4%BA%AC&trainNum=D717&date=2020-11-15&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E4%BA%8C%E7%AD%89%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "二等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "4",
        price: "233",
        countColor: -1,
        studentPrice: "175",
        tagColor: -1,
        count: 0,
      },
      {
        type: "二等卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "38",
        price: "408",
        countColor: -1,
        studentPrice: "408",
        tagColor: -1,
        count: 0,
      },
      {
        type: "一等卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "36",
        price: "540",
        countColor: -1,
        studentPrice: "540",
        tagColor: -1,
        count: 0,
      },
      {
        type: "无座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "0",
        price: "233",
        countColor: -1,
        studentPrice: "233",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: false,
    remainTicketColor: -39424,
    aStation: "南京",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002110445",
    remainTicketType: 0,
    aTime: "04:45",
    dayAfter: "+1",
    tagColor: -1,
    trainNumber: "D717",
    arrStationCode: "NJH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "AOH",
    remainTicketCount: 0,
    dTimeStr: "202002101936",
    sort: 7,
    time: "9时21分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京南",
    date: "2020-11-16",
    remainTicket: "0张",
    priceMsg: "¥231",
    dptStationCode: "VNP",
    trainType: "动车组",
    timeInMinute: 561,
    dStationInfo: true,
    trainStatus: 4,
    dTime: "19:36",
    startStationCode: "VNP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: false,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "2057",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC%E5%8D%97&endStation=%E5%8D%97%E4%BA%AC&trainNum=D707&date=2020-11-16&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E4%BA%8C%E7%AD%89%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "二等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "4",
        price: "231",
        countColor: -1,
        studentPrice: "174",
        tagColor: -1,
        count: 0,
      },
      {
        type: "二等卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "38",
        price: "405",
        countColor: -1,
        studentPrice: "405",
        tagColor: -1,
        count: 0,
      },
      {
        type: "一等卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "36",
        price: "536",
        countColor: -1,
        studentPrice: "536",
        tagColor: -1,
        count: 0,
      },
      {
        type: "无座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "0",
        price: "231",
        countColor: -1,
        studentPrice: "231",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: true,
    remainTicketColor: -39424,
    aStation: "南京",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002110457",
    remainTicketType: 0,
    aTime: "04:57",
    dayAfter: "+1",
    tagColor: -1,
    trainNumber: "D707",
    arrStationCode: "NJH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "SHH",
    remainTicketCount: 0,
    dTimeStr: "202002102005",
    sort: 12,
    time: "11时38分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京",
    date: "2020-11-16",
    remainTicket: "0张",
    priceMsg: "¥148.5",
    dptStationCode: "BJP",
    trainType: "空调特快",
    timeInMinute: 698,
    dStationInfo: true,
    trainStatus: 4,
    dTime: "20:05",
    startStationCode: "BJP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: false,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "1629",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC&endStation=%E5%8D%97%E4%BA%AC&trainNum=T109&date=2020-11-16&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E7%A1%AC%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "硬座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "1",
        price: "148.5",
        countColor: -1,
        studentPrice: "75",
        tagColor: -1,
        count: 0,
      },
      {
        type: "硬卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "5",
        price: "272.5",
        countColor: -1,
        studentPrice: "199",
        tagColor: -1,
        count: 0,
      },
      {
        type: "软卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "8",
        price: "415.5",
        countColor: -1,
        studentPrice: "415.5",
        tagColor: -1,
        count: 0,
      },
      {
        type: "高级软卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "10",
        price: "765.5",
        countColor: -1,
        studentPrice: "765.5",
        tagColor: -1,
        count: 0,
      },
      {
        type: "无座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "0",
        price: "148.5",
        countColor: -1,
        studentPrice: "75",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: false,
    remainTicketColor: -39424,
    aStation: "南京",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002110743",
    remainTicketType: 0,
    aTime: "07:43",
    dayAfter: "+1",
    tagColor: -1,
    trainNumber: "T109",
    arrStationCode: "NJH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "SHH",
    remainTicketCount: 0,
    dTimeStr: "202002102121",
    sort: 8,
    time: "9时24分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京",
    date: "2020-11-14",
    remainTicket: "0张",
    priceMsg: "¥233",
    dptStationCode: "BJP",
    trainType: "动车组",
    timeInMinute: 564,
    dStationInfo: true,
    trainStatus: 4,
    dTime: "21:21",
    startStationCode: "BJP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: false,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "2068",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC&endStation=%E5%8D%97%E4%BA%AC&trainNum=D705&date=2020-11-14&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E4%BA%8C%E7%AD%89%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "二等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "4",
        price: "233",
        countColor: -1,
        studentPrice: "175",
        tagColor: -1,
        count: 0,
      },
      {
        type: "二等卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "38",
        price: "408",
        countColor: -1,
        studentPrice: "408",
        tagColor: -1,
        count: 0,
      },
      {
        type: "一等卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "36",
        price: "501",
        countColor: -1,
        studentPrice: "501",
        tagColor: -1,
        count: 0,
      },
      {
        type: "无座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "0",
        price: "233",
        countColor: -1,
        studentPrice: "233",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: false,
    remainTicketColor: -39424,
    aStation: "南京",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002110645",
    remainTicketType: 0,
    aTime: "06:45",
    dayAfter: "+1",
    tagColor: -1,
    trainNumber: "D705",
    arrStationCode: "NJH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "NJH",
    remainTicketCount: 0,
    dTimeStr: "202002102244",
    sort: 10,
    time: "9时30分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京南",
    date: "2020-11-13",
    remainTicket: "0张",
    priceMsg: "¥231",
    dptStationCode: "VNP",
    trainType: "动车组",
    timeInMinute: 570,
    dStationInfo: true,
    trainStatus: 4,
    dTime: "22:44",
    startStationCode: "VNP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: true,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "2090",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC%E5%8D%97&endStation=%E5%8D%97%E4%BA%AC&trainNum=D715&date=2020-11-13&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E4%BA%8C%E7%AD%89%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "二等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "4",
        price: "231",
        countColor: -1,
        studentPrice: "174",
        tagColor: -1,
        count: 0,
      },
      {
        type: "二等卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "38",
        price: "405",
        countColor: -1,
        studentPrice: "405",
        tagColor: -1,
        count: 0,
      },
      {
        type: "一等卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "36",
        price: "536",
        countColor: -1,
        studentPrice: "536",
        tagColor: -1,
        count: 0,
      },
      {
        type: "无座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "0",
        price: "231",
        countColor: -1,
        studentPrice: "231",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: true,
    remainTicketColor: -39424,
    aStation: "南京",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002110814",
    remainTicketType: 0,
    aTime: "08:14",
    dayAfter: "+1",
    tagColor: -1,
    trainNumber: "D715",
    arrStationCode: "NJH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "RZH",
    remainTicketCount: 0,
    dTimeStr: "202002102320",
    sort: 13,
    time: "14时27分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -14964294,
    dStation: "北京",
    date: "2020-11-13",
    remainTicket: "0张",
    priceMsg: "¥148.5",
    dptStationCode: "BJP",
    trainType: "快速",
    timeInMinute: 867,
    dStationInfo: true,
    trainStatus: 4,
    dTime: "23:20",
    startStationCode: "BJP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: false,
    tagCode: -1,
    trainShowDesc: "可抢票",
    robSuccRate: "",
    distance: "1734",
    action: {
      menuBackColor: -16728876,
      menuColor: -1,
      clickable: false,
      touchUrl:
        "http://touch.qunar.com/h5/train/flagship/TrainOrderFillRob?startStation=%E5%8C%97%E4%BA%AC&endStation=%E5%8D%97%E4%BA%AC&trainNum=K101&date=2020-11-13&closeUrl=&source=mtrain_rob&bd_source=&seatType=%E7%A1%AC%E5%BA%A7",
      menu: "抢票",
      topDesc: "0张",
      topDescBackColor: 0,
      topDescColor: -52480,
      id: 2,
    },
    trainStatusDes: "已售空",
    appointment: false,
    ticketInfos: [
      {
        type: "硬座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "1",
        price: "148.5",
        countColor: -1,
        studentPrice: "75",
        tagColor: -1,
        count: 0,
      },
      {
        type: "硬卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "5",
        price: "272.5",
        countColor: -1,
        studentPrice: "199",
        tagColor: -1,
        count: 0,
      },
      {
        type: "软卧",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "8",
        price: "415.5",
        countColor: -1,
        studentPrice: "415.5",
        tagColor: -1,
        count: 0,
      },
      {
        type: "无座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "0",
        price: "148.5",
        countColor: -1,
        studentPrice: "75",
        tagColor: -1,
        count: 0,
      },
    ],
    isSupportCard: false,
    remainTicketColor: -39424,
    aStation: "南京",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002111347",
    remainTicketType: 0,
    aTime: "13:47",
    dayAfter: "+1",
    tagColor: -1,
    trainNumber: "K101",
    arrStationCode: "NJH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
  {
    endStationCode: "AOH",
    remainTicketCount: 0,
    dTimeStr: "202002101716",
    sort: 3,
    time: "4时27分",
    isPreOrder: false,
    extra: "{}",
    trainShowDescColor: -1,
    dStation: "北京南",
    date: "2020-11-13",
    remainTicket: "",
    priceMsg: "¥443.5",
    dptStationCode: "VNP",
    trainType: "高速动车",
    timeInMinute: 267,
    dStationInfo: true,
    trainStatus: 2,
    dTime: "17:16",
    startStationCode: "VNP",
    isSupportCandidate: false,
    dCity: "北京",
    aStationInfo: false,
    tagCode: -1,
    robSuccRate: "",
    distance: "1335",
    trainStatusDes: "已停售",
    appointment: false,
    ticketInfos: [
      {
        type: "二等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "4",
        price: "443.5",
        countColor: -1,
        studentPrice: "333",
        tagColor: -1,
        count: -1,
      },
      {
        type: "一等座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "3",
        price: "748.5",
        countColor: -1,
        studentPrice: "748.5",
        tagColor: -1,
        count: -1,
      },
      {
        type: "商务座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "13",
        price: "1403.5",
        countColor: -1,
        studentPrice: "1403.5",
        tagColor: -1,
        count: -1,
      },
      {
        type: "无座",
        paperAccept: 0,
        defaultSeatCheckStatus: 0,
        typeColor: -1,
        wxSaleStatus: 0,
        isUncheckable: 0,
        ticketId: "0",
        price: "443.5",
        countColor: -1,
        studentPrice: "443.5",
        tagColor: -1,
        count: -1,
      },
    ],
    isSupportCard: true,
    remainTicketColor: 0,
    aStation: "南京南",
    tagStyleType: 0,
    noTicketSceneOptimise: false,
    aCity: "南京",
    aTimeStr: "202002102143",
    remainTicketType: 0,
    aTime: "21:43",
    dayAfter: "",
    tagColor: -1,
    trainNumber: "G153",
    arrStationCode: "NKH",
    sortGroup: 0,
    remainTicketBackgroundColor: 0,
  },
];
